backend:
  name: git-gateway

media_folder: "static/myndir"
public_folder: "myndir"

collections:
  - name: "dagur"
    label: "Dagur í desember"
    folder: "static/content/dagar"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Dagsetning",
          name: "dagsetning",
          widget: "date",
          format: "M/D",
          hint: "Veldu þann dag í desember sem á við",
        }
      - label: "Video"
        name: "vidjo"
        widget: "object"
        fields:
          - {
              label: "Lýsing",
              name: "vidjotitill",
              widget: "text",
              required: false,
            }
          - {
              label: "VidjoURL",
              name: "vidjourl",
              widget: "string",
              required: false,
            }
  - name: "event"
    label: "Viðburður"
    folder: "static/content/events"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Hvenær", name: "hvenaer", widget: "date", format: "M/D" }
      - {
          label: "Klukkan",
          name: "klukkan",
          widget: "string",
          hint: "setjið inn á þessu formatti: 16-18",
        }
      - { label: "Stutt lýsing", name: "body", widget: "markdown" }
      - { label: "Hvar", name: "hvar", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
  - name: "verkefni-dagins"
    label: "Verkefni Dagsins"
    folder: "static/content/verkefni-dagsins"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Lýsing", name: "lysing", widget: "text" }
      - {
          label: "Dagsetning",
          name: "dagsetning",
          widget: "date",
          format: "M/D",
        }
