backend:
  name: git-gateway

media_folder: "static/myndir"
public_folder: "myndir"

collections:
  - name: "dagur"
    label: "Dagur í desember"
    folder: "static/content/dagar"
    create: true
    fields:
      - { label: "Titill", name: "titill", widget: "string" }
      - label: "Vidjo"
        name: "vidjo"
        widget: "object"
        fields:
          - { label: "Vidjo Titill", name: "vidjo-titill", widget: "string" }
          - { label: "Vidjo URL", name: "vidjo-url", widget: "file" }
