backend:
  name: git-gateway

media_folder: "static/myndir"
public_folder: "myndir"

collections:
  - name: "dagur"
    label: "Dagur í desember"
    folder: "static/content/dagar"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Dagsetning", name: "dagsetning", widget: "date" }
      - label: "Vidjo"
        name: "vidjo"
        widget: "object"
        fields:
          - { label: "Vidjo Titill", name: "vidjotitill", widget: "string" }
          - { label: "Vidjo URL", name: "vidjourl", widget: "file" }
